<h2 style="color:green" align="center">Machine Learning With Python: Save And Load Trained Model</h2>

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [6]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [7]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [8]:
model.coef_

array([135.78767123])

In [9]:
model.intercept_

180616.43835616432

In [10]:
model.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Model To a File Using Python Pickle</h3>

In [11]:
import pickle

In [12]:
with open('model_pickle','wb') as file: #write binary (Wb)
    pickle.dump(model,file)

<h4 style='color:purple'>Load Saved Model</h4>

In [13]:
with open('model_pickle','rb') as file: #Reaad Binary(rb)
    mp = pickle.load(file)

In [14]:
mp.coef_

array([135.78767123])

In [15]:
mp.intercept_

180616.43835616432

In [16]:
mp.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Trained Model Using joblib</h3>

In [17]:
import sklearn
sklearn.__version__

'0.23.2'

In [19]:
from sklearn.externals import joblibfrom sklearn.externals 
import joblibfrom sklearn.externals 
import joblibfrom sklearn.externals 
import joblib

SyntaxError: invalid syntax (<ipython-input-19-addaade54ca5>, line 1)

In [20]:
import joblib

In [22]:
joblib.dump(model, 'model_joblib')

['model_joblib']

<h4 style='color:purple'>Load Saved Model</h4>

In [23]:
mj = joblib.load('model_joblib')

In [25]:
mj.coef_

array([135.78767123])

In [26]:
mj.intercept_

180616.43835616432

In [27]:
mj.predict([[5000]])

array([859554.79452055])